[package]
name = "x_transfer"
version.workspace = true
edition.workspace = true

[dependencies]
x_core = { path = "../core" }
ethers = "2.0"
anyhow = "1.0"
tokio = { version = "1.0", features = ["full"] }
