[package]
name = "tx-tx-tx"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tx-tx-tx"
path = "src/main.rs"

[dependencies]
x_cli = { path = "../cli" }
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
tokio = { version = "1.35", features = ["full"] }
