[package]
name = "x_signature"
version.workspace = true
edition.workspace = true

[dependencies]
x_core = { path = "../core" }
ethers = "2.0"
sha3 = "0.10"
secp256k1 = { version = "0.27", features = ["recovery"] }
anyhow = "1.0"
hex = "0.4"
