[package]
name = "x_core"
version.workspace = true
edition.workspace = true

[dependencies]
sha3 = "0.10"
dotenvy = "0.15"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
ethers = "2.0"
